name: Static code analysis

on:
  push:
    branches: [main]
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# You need these permissions to publish to GitHub pages
permissions:
    contents: write
    pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          path: probabilistic_piping

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          manifest-path: probabilistic_piping/pixi.toml
          pixi-version: "latest"

      - name: Ruff Lint
        run: pixi run ruff check --output-format=github .
        working-directory: probabilistic_piping
      - name: Check format
        run: pixi run ruff format --check
        working-directory: probabilistic_piping
