name: Run Pytest

on:
  push:
    branches: [main]
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# You need these permissions to publish to GitHub pages
permissions:
    contents: write
    pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          manifest-path: pixi.toml
          pixi-version: "latest"

      - name: Run Pytests
        run: pixi run pytest --cov
